import numpy as np

ACTION_FACTOR = 25 / 100

LOW_PRICE = 0
HIGH_PRICE = np.inf
LOW_CAPACITY = 0
HIGH_CAPACITY = 300
LOW_TICKETS_SOLD = LOW_CAPACITY
HIGH_TICKETS_SOLD = HIGH_CAPACITY
LOW_ACTION_MASK = 0
HIGH_ACTION_MASK = 1

LOW_ACTION = -1
HIGH_ACTION = 1
